[package]
name = "tauri-plugin-iced"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
description = "Tauri plugin for Iced GUI framework"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.77.2"
links = "tauri-plugin-iced"

[dependencies]
log = "0.4"

tauri = { workspace = true }
tauri-runtime = { workspace = true }
tauri-runtime-wry = { workspace = true }

# Iced dependencies
iced = { workspace = true }
iced_tiny_skia = { workspace = true }
iced_winit = { workspace = true }
iced_widget = { workspace = true }
iced_runtime = { workspace = true }
iced_graphics = { workspace = true }
iced_core = { workspace = true }
iced_renderer = { workspace = true }

# Graphics and utilities
softbuffer = { workspace = true }
tiny-skia = { workspace = true }
bytemuck = { workspace = true }
anyhow = "1.0"
serde = { version = "1", features = ["derive"] }


[target.'cfg(any(target_os = "macos"))'.dependencies]
cocoa = "0.25"
objc = "0.2"
objc2 = "0.6.3"
objc2-quartz-core = { version = "0.2", features = ["CATransaction"] }

[build-dependencies]
tauri-plugin = { version = "2.3.0", features = ["build"] }
